### ISSUE TITLE
Regex becomes broken when uglified

### ISSUE THREAD

**Issue by sirxemic** [iambumblehead/form-urlencoded#10]
So UglifyJS has this tendency to replace any `\uXXXX` substring with the UTF-8 equivalent. However, code points such as `\uDC00`, `\uDFFF`, `\uD800`, `\uDBFF` are surrogate characters and therefore don't have a UTF-8 equivalent. UglifyJS therefore replaces these substrings with �, which turns the regex line into:

```js
s = new RegExp(['(?:[\0-"-&+-}-퟿-￿]|', "[�-�][�-�]|[�-�](?![�-�])|", "(?:[^�-�]|^)[�-�])"].join(""), "g"),
```

This regex is not the same as the regex in the source code. The `�-�` part which used to mean `\uDC00-\uDFFF` now essentially means `\uFFFD-\uFFFD`...

Now of course you could argue that this is something UglifyJS should fix on their end, but it has been mentioned several times and they don't seem to ever fix it. They just suggest to use the `--ascii-only` parameter to suppress this transformation.

I think a library such as this one will be used in a lot of projects where the source code will be uglified. People won't notice that this transformation is invalid and therefore won't use the `--ascii-only` parameter either. 

You can fix this in the library itself by escaping the backslashes. Basically this:

```js
encodechar = new RegExp(['(?:[\\0-\\x1F"-&\\+-\}\\x7F-\\uD7FF\\uE000-\\uFFFF]|',
    '[\\uD800-\\uDBFF][\\uDC00-\\uDFFF]|[\\uD800-\\uDBFF](?![\\uDC00-\\uDFFF])|',
    '(?:[^\\uD800-\\uDBFF]|^)[\uDC00-\\uDFFF])'].join(''), 'g')
```

Alternatively you can replace it with regex notation. UglifyJS won't transform those:

```js
encodechar = /(?:[\0-\x1F"-&\+-\}\x7F-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])/g
```

So since this technically is not a bug on your end, you can just ignore this if you want. However, I am hoping you will apply this fix to prevent more headaches in the future.

**Comment by iambumblehead** [comment]
@sirxemic thanks for explaining this to me. If you make a pull request, I'll merge it. Otherwise, I'll commit your recommended change myself in the next day or two.

**Comment by iambumblehead** [comment]
Maybe the smaller unicode regexp should be used now `/[^ !'()~\*]/gu` Internet Explorer is the most common browser missing unicode flag support `/u`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode

**Comment by iambumblehead** [comment]
resolved https://github.com/iambumblehead/form-urlencoded/commit/448568b199c9ec2b117904c1a4825ca54c18775d
