### ISSUE TITLE
Provide ES5 source?

### ISSUE THREAD

**Issue by elado** [iambumblehead/form-urlencoded#11]
Currently the source provided is ES6. The default config of webpack & babel-loader is not to transpile anything in node_modules. And when using ES6, this package breaks when compiling/uglifying.

Usually packages transpile their code using a `postinstall` command, `"postinstall": "babel -d lib/ src/"` and point the `main` field to `lib`. `lib` is in `.gitignore` too.

Open to this?

**Comment by iambumblehead** [comment]
yes if you would make a pull request I would take one, otherwise I would add this myself over the next day or two.

**Comment by iambumblehead** [comment]
resolved https://github.com/iambumblehead/form-urlencoded/pull/12/files
