### ISSUE TITLE
encoded another language is wrong

### ISSUE THREAD

**Issue by Tataro** [iambumblehead/form-urlencoded#14]
Hi
i try to encode the object that include this word `นาย กิตติทัต อุปพงศ์` 
the right encoded must be `%B9%D2%C2+%A1%D4%B5%B5%D4%B7%D1%B5+%CD%D8%BB%BE%A7%C8%EC`
but i got `%E0%B8%99%E0%B8%B2%E0%B8%A2+%E0%B8%81%E0%B8%B4%E0%B8%95%E0%B8%95%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%95+%E0%B8%AD%E0%B8%B8%E0%B8%9B%E0%B8%9E%E0%B8%87%E0%B8%A8%E0%B9%8C`

can you help me with this?

**Comment by iambumblehead** [comment]
@Tataro I'm interested in resolving this --would you tell me more? would you point me to a resource which encodes your string correctly?

**Comment by iambumblehead** [comment]
both of these scripts encode 'นาย กิตติทัต อุปพงศ์' in the way form-urlencoded does,
https://npm.runkit.com/strict-uri-encode
https://npm.runkit.com/query-string

query-string decodes the encoded value back to the original form,
```javascript 
queryString.parse('val=%E0%B8%99%E0%B8%B2%E0%B8%A2+%E0%B8%81%E0%B8%B4%E0%B8%95%E0%B8%95%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%95+%E0%B8%AD%E0%B8%B8%E0%B8%9B%E0%B8%9E%E0%B8%87%E0%B8%A8%E0%B9%8C')
// val: "นาย กิตติทัต อุปพงศ์"
```

**Comment by iambumblehead** [comment]
@Tataro feel free to re-open this issue for any reason

A few days have passed and I'll assume you've found a solution :)

**Comment by Tataro** [comment]
@iambumblehead thks for reply, sry for my late
i found that
`%B9%D2%C2+%A1%D4%B5%B5%D4%B7%D1%B5+%CD%D8%BB%BE%A7%C8%EC`
[reference](http://www.ascii.ca/cp874.htm)
is ascii encode lol

so, it's my fault for misunderstand
thks again 👍

**Comment by iambumblehead** [comment]
@Tataro thanks! I'm glad you found a solution :)
