### ISSUE TITLE
skipIndex usage needs a fix

### ISSUE THREAD

**Issue by venky352** [iambumblehead/form-urlencoded#15]
When I use this module and provide an option `skipIndex`. I see issue with urlencoded data.

The use case that I have is for input payload like `x=y&x=y`, traditional body parsers convert this into a JSON as `{x: [y,y]}`. If I convert this into urlencoded data again using this module with option `skipIndex` set to `true`. I expect the response to be like `x=y&x=y`, but instead it is like `x[]=y&x[]=y`. Is the array indexing is still needed here? Referring the implementation where the indexing added here https://github.com/iambumblehead/form-urlencoded/blob/master/form-urlencoded.js#L27

**Comment by iambumblehead** [comment]
@venky252 this form-urlencoded output is correct to my knowledge: `{x: [y,y]}` becomes `x[]=y&x[]=y`

when skipIndex is false, the output is `x[0]=y&x[1]=y` per [discussion here][1]. If you're certain the given output is wrong and would provide a link to something authoritative I'd be interested to resolve the issue. 


[1]: https://github.com/iambumblehead/form-urlencoded/pull/7

**Comment by iambumblehead** [comment]
@venky352 feel welcome to reopen this issue if you think necessary
