### ISSUE TITLE
the change to exports.default breaks rollup, possibly other build tools

### ISSUE THREAD

**Issue by cmawhorter** [iambumblehead/form-urlencoded#17]
fwiw, the recent change to `module.exports.default = ...` breaks rollup.

i'm not entirely sure about other envs, but with rollup, you need `module.exports = fn...` and the default is implied.  (i believe webpack is the same, though it may sniff for `.default`.  donno.)

after this change, you need to do this to support latest release and past releases:

```js
import { default as _formurlencoded } from 'form-urlencoded';
const formurlencoded = 'default' in _formurlencoded ? _formurlencoded.default : _formurlencoded;
```

**Comment by iambumblehead** [comment]
@cmawhorter yikes... do you have any recommendations?

The change comes from this PR https://github.com/iambumblehead/form-urlencoded/pull/16

cc @AndrewDebens

**Comment by iambumblehead** [comment]
@cmawhorter what if form-urlencoded defined an es6 "module" script on the module property in the package.json --would that be sufficient?

[0]: https://github.com/rollup/rollup/wiki/pkg.module "rollup, module"

**Comment by iambumblehead** [comment]
@cmawhorter I published a new version that with ["module" defined in the package.json][1] and updated the source file to [use es6 export.][0]

Does it resolve the issue?

[0]: https://github.com/iambumblehead/form-urlencoded/blob/master/form-urlencoded.js#L5 "export"
[1]: https://github.com/iambumblehead/form-urlencoded/blob/master/package.json#L4 "module"

**Comment by cmawhorter** [comment]
i'd recommend changing it back to support backwards compat (since that pr likely breaks anyone doing a `require('form-urlencoded')` as well.  

i'm confused what the author of the PR was hoping to achieve.  he wants typescript to identify the lib as a function instead of any?  afaik, `any` is a perfectly acceptable and common type in typescript.

**Comment by cmawhorter** [comment]
ah, nice.  i see you just published a rolled up version.  what that does is define the __esModule.  that combined with the `package.module` should get me where i need to be at least.  i'll give it a shot tomorrow.

**Comment by iambumblehead** [comment]
@cmawhorter thanks for your input and help

**Comment by AndrewDebens** [comment]
Being forced to use require means you drop the associated type. There is not much point in using typescript if you're not going to really use it. 

If this is really a breaking change I would also recommend reverting, but only if the typing are updated to match the module. I'm also happy to just fix the version number in my project.

**Comment by cmawhorter** [comment]
who's using typescript?  not i.  

i actually just tested this now and it's just about right.  what you want to do is ship two different builds.  one for es compatible envs and one for cjs envs.

something like this for the rollup config:

```js
import babel from 'rollup-plugin-babel';
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import builtins from 'rollup-plugin-node-builtins';

export default {
  entry:              'form-urlencoded.js',
  sourceMap:          true,
  plugins: [
    // optional.  not sure if lib needs it. json(),
    // optional.  not sure if lib needs it. builtins(),
    // optional.  not sure if lib needs it. nodeResolve({ jsnext:         true, main:           true, browser:        true }),
    // optional.  not sure if lib needs it. commonjs({ include:        'node_modules/**' }),
    babel({
      exclude:        'node_modules/**',
      babelrc:        false,
      presets:        [ [ 'es2015', { modules: false } ] ],
      plugins:        [ 'external-helpers' ],
    }),
  ],
  targets: [
    { dest: 'dist/form-urlencoded.cjs.js', format: 'cjs' },
    { dest: 'dist/form-urlencoded.es.js', format: 'es' },
  ],
}
```

and then in in package.json

```
"main": "dist/form-urlencoded.cjs.js"
"module": "dist/form-urlencoded.es.js",
```

That maintains compat with existing node/require while also forward with tools supporting the non-standard module.  (all of them?)

**Comment by iambumblehead** [comment]
@cmawhorter thank you. Does form-urlencoded need the rollup config? Besides filepaths, would the result be different from the current configuration that includes [these in package.json?][0]
```
  "main": "dist/form-urlencoded",
  "module": "src/form-urlencoded",
```

[0]: https://github.com/iambumblehead/form-urlencoded/blob/master/package.json#L3-L4

**Comment by iambumblehead** [comment]
I think the current situation is working for rollup and typescript users and everyone else... but I'm not sure :)

Would anyone confirm? @AndrewDebens @cmawhorter @josec89? thanks for any response

**Comment by AndrewDebens** [comment]
Its working for typescript and webpack :)

**Comment by iambumblehead** [comment]
@AndrewDebens thank you for responding. With that let's close this.

@cmawhorter please feel free to reopen if necessary and thanks for reporting.
