### ISSUE TITLE
Differences between 2.07 and 2.04

### ISSUE THREAD

**Issue by avilaj** [iambumblehead/form-urlencoded#18]
Hi, i'm having troubles with version 2.0.7 it seems to be exporting an object with { default }
I had to roll back to 2.0.4

Have this happened to you?
(im using node 8.9.4)

**Comment by iambumblehead** [comment]
@avilaj the problem stems from changes discussed in this issue https://github.com/iambumblehead/form-urlencoded/issues/17

To my knowledge es6 import is incompatible with commonjs and it is becoming more common to upgrade to es6 and expect the user to import default when using commonjs. What do you think? 

It would be possible to generate a script that does not export default, but I've noticed other projects are beginning to require import default, for example [infernojs][0] works this way now.

Please share your thoughts. I'd like the script to work in a straightforward way for as many people as possible.

[0]: https://github.com/infernojs/inferno

**Comment by iambumblehead** [comment]
cc @AndrewDebens

I apologize to bother you. Please chime in if you have any suggestions or ideas.

**Comment by AndrewDebens** [comment]
I'm not currently aware of any clean solution to this, but there are a few approaches. 

The cleanest I can come up with is to revert the offending pull request, and use node method of module.exports, supporting commonJS. This forces an ES6 consumer to use a transpiler to check for the __esModule flag presence, but honestly who isn't using something like babel these days.

Now this does mean that for peak performance a typescript user would have to compile their code first to ES6 and then transpile  it down further using babel (or equivalent), but they should really not use typescript to go further back than ES6 as any further and you loose tree shaking. And if you really don't care about tree shaking then you can use the esModuleInterop in the tsconfig.

I do agree that people are moving towards ES6, and rightly so, but this was a breaking change, and hence should have been done as a major version update. And maybe also have a lib/ folder that would have commJS compatible exports to users could scope into if required?

**Comment by iambumblehead** [comment]
@AndrewDebens thanks. Some tools I use such as vscode seem to work better with es6.

The only way I know of to "tell" the build tool which script to use (ES6-version or CommonJS-version) is by using the "module" property and I'm not sure if all build tools will use that or only rollup. If we generated a CommonJS version I don't know how to guarantee it will be used for CommonJS environments only...

I imagine it will be easier to add a readme note to use `require('form-urlencoded').default` with CommonJS. @avilaj do you think that would be sufficient?

**Comment by iambumblehead** [comment]
@avilaj I've been doing this all wrong --I'll follow your recommendation.

**Comment by iambumblehead** [comment]
@avilaj I created [two tags, 1.0.9 and 2.0.0] and published each to npm.

1.0.9 uses the commonjs module.exports,
2.0.0 uses the es6 export default.

Does it seem OK to you?

[0]: https://github.com/iambumblehead/form-urlencoded/releases

**Comment by avilaj** [comment]
Thanks @iambumblehead, that sounds correct to me. I'm gonna try them today!
I'll let you know.

Best,

**Comment by iambumblehead** [comment]
@avilaj it would be awesome if you would confirm and close this :)
