### ISSUE TITLE
module field in package.json points to a non-existent file

### ISSUE THREAD

**Issue by frabarz** [iambumblehead/form-urlencoded#19]
The `"module"` field in the [package.json](https://github.com/iambumblehead/form-urlencoded/blob/master/package.json#L4) file points to a `src/form-urlencoded.js` file, which doesn't exists in either the repository or the npm package. This is currently conflicting with some functionality in rollup.

This field should be pointing to the esm version of the library, which is now the `form-urlencoded.js` file in the root folder.

**Comment by iambumblehead** [comment]
@frabarz thank you the field is updated and published to a new version of this package
