### ISSUE TITLE
Name of the arrays always ends with []

### ISSUE THREAD

**Issue by darkman97i** [iambumblehead/form-urlencoded#22]
Really, is mandatory the name of attributes of type array always ending with []?

In this section of code is forcing always to set at the end of the name of arrays attribute the []
```
arrnest = (name, arr) => arr.length
            ? filterjoin(arr.map((elem, index) => skipIndex
                ? nest(name + '[]', elem)
                : nest(name + '[' + index + ']', elem)))
            : encode(name + '[]'),
```

When I sending attributes with Jersey - JAVA - I'm doing in this way:
```
for (String user : users) {
    formParam.add("usersId", user);
}
```

The next image show data collected from server:
![Selección_030](https://user-images.githubusercontent.com/958703/66244158-724dcf00-e707-11e9-9ad1-84d19849c01e.png)

After reading some of the closed issues #8 , specially the end of the #7, I changed the code with:
```
formurlencoded(formData, { skipIndex: true }),
```

That worked nearly the expected, but the name includes always the [] at the end.
![Selección_031](https://user-images.githubusercontent.com/958703/66244327-26e7f080-e708-11e9-9d9d-4c13b7a51f92.png)

And here my question, something might be wrong, or my code in Jersey or [] added by your package should not be mandatory ( might be there's some RFC what forces the [] at the end if is an array? ). Or maybe both scenarios are acceptable?

I make a small improvement in the server side to working with both name format, but I will appreciate your opinion about it.

Thanks for your time.

**Comment by iambumblehead** [comment]
@darkman97i I don't know the answer. To my understanding list handling isn't really specified anywhere. My development of this script focused on making it work with services I was using and those services needed lists to include '[]' after the name.

**Comment by darkman97i** [comment]
Nobody thinks in Arrays and Map until you must send one of them, I have worked in past with different REST libraries and there's a little mess about how each one decides to solve this types. 

Anyway, my opinion is that is quite strange the name of the attribute be modified on fly. I think usually you will expect that what you send ( in terms of the name ) and what you receive to be the same, that's why adding extra "[]" at the end always might be not good in some scenarios.

My suggestion will be to introduce a parameter to disable [] at the end, something named like **skipBracket** (http://wason21cn.blogspot.com/2008/01/english-name-for-character-in-keyboard.html ).

```
arrnest = (name, arr) => arr.length
            ? filterjoin(arr.map((elem, index) => skipIndex
                ? => skipBracket
			? nest(name, elem)
			: nest(name + '[]', elem)
                : nest(name + '[' + index + ']', elem)))
            : encode(name + '[]'),
```

Take as a suggestion, in my case I applied a workaround in the server-side.

**Comment by iambumblehead** [comment]
@darkman97i thank you for your suggestion. If you'd like to make a PR that would be great otherwise I can modify the script later this evening. What do you think of this?

```javascript
bracketAffix = skipBracket ? '' : '[]',

arrnest = (name, arr) => arr.length
    ? filterjoin(arr.map((elem, index) => skipIndex
        ? nest(name + bracketAffix, elem)
        : nest(name + '[' + index + ']', elem)))
  : encode(name + bracketAffix),
```

**Comment by darkman97i** [comment]
I forget to modify the README.cmd file
