### ISSUE TITLE
optional formatting for nested object

### ISSUE THREAD

**Issue by doddys** [iambumblehead/form-urlencoded#25]
Hi, Thanks for a very useful libs. However, when I tried to use the library on my project. I come into a requirement like the following

sample json:
```
{
   "a" : [
        {
             "aa" : 1,
             "ab" : 2
        },
        {
            "ac" : 3
        }
    ]
}
```

The current code will format the field name as "**a[0][aa]**" before the encoding. 
What I need was in the format of "**a[0].name**" before the encoding.

I added the another option for this in my fork repo. Let me know if this is something that can be merged. 

Thanks

**Comment by iambumblehead** [comment]
@doddys perhaps there is a package already which generates property lookup strings in the way you need. This package comes close, but formats array index values in the same way as named properties: https://www.npmjs.com/package/stringify-keys

If there is no suitable package, feel free to make pull request

I will try to find a serlializer package using the lookup format you need

**Comment by iambumblehead** [comment]
@doddys I couldn't find a package that serializes strings this way.

Thanks for messaging me here. Feel free to make a pull request.

**Comment by doddys** [comment]
thanks @iambumblehead, I have submitted the pull request.

**Comment by iambumblehead** [comment]
the pull request is merged and published. closing.
