### ISSUE TITLE
Should space be replaced as %20 or + sign?

### ISSUE THREAD

**Issue by doddys** [iambumblehead/form-urlencoded#27]
Hi @iambumblehead,

I am just wondering why space is replace by + sign instead of %20? 

Thanks

Doddy

**Comment by iambumblehead** [comment]
@doddys its specified behaviour https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#url-encoded-form-data

closing but feel free to reopen if needed

**Comment by ash0080** [comment]
Not work for many old servers，
Could this be configurable？

**Comment by perrin4869** [comment]
I am also dealing with an older server which doesn't seem to understand `+`... Would you accept a PR to make this configurable?

**Comment by iambumblehead** [comment]
@perrin4869 yes please make a PR

**Comment by iambumblehead** [comment]
@ash0080 @perrin4869 @doddys somehow I missed the follow-up comments until this morning. I see now it would be useful to support whitespace configurations.

**Comment by iambumblehead** [comment]
whitespace is configurable now, closing
