### ISSUE TITLE
No need for [] when skipping index for an array

### ISSUE THREAD

**Issue by binarykitchen** [iambumblehead/form-urlencoded#28]
When I have a multi-value attribute like

```js
const formData = {
  name: ['apple', 'bananas']
}
```

and run this through `formurlencoded(formData, { skipIndex: true })`

then I expect this to be 

```
name=apple&name=bananas
// in parsed form:
// name: apple
// name: bananas
```

but not 

```
name%5B%5D=apple&name%5B%5D=bananas
// in parsed form:
// name[]: apple
// name[]: bananas
```

**Comment by binarykitchen** [comment]
To reproduce: Go to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_form_checkbox

then use this HTML

```
<!DOCTYPE html>
<html>
<body>
<form action="/action_page.php" method="get">
  <input type="text" name="test" value="Bike">
  <input type="text" name="test" value="Bike2">
  <input type="text" name="test" value="Bike3">
  <input type="text" name="test" value="Bike4">
  <input type="submit" value="Submit">
</form>
</body>
</html>
```

that will yield test=Bike&test=Bike2&test=Bike3&test=Bike4

**Comment by iambumblehead** [comment]
@binarykitchen I'm not sure when I will be available to look into this. Is it an important issue for you?

Do you think the change would be safe for packages using this package?

**Comment by binarykitchen** [comment]
@iambumblehead i think this will become a breaking change. recommend a new version with that behaviour and to add new options for those who want the old behaviour.

yep, important here. i could do a PR today to speeden things up. would you accept that?

**Comment by iambumblehead** [comment]
@binarykitchen that's very kind of you. Yes, a PR with a test would be accepted.

**Comment by binarykitchen** [comment]
@iambumblehead lol, forget it. discovered a hidden parameter `skipBracket` in your code. works now for me. maybe you should document it one day ...

**Comment by iambumblehead** [comment]
I'm sorry for your trouble @binarykitchen. yes it should be documented.
