### ISSUE TITLE
Disable the wiki

### ISSUE THREAD

**Issue by BenMcH** [iambumblehead/form-urlencoded#34]
I would suggest disabling the wiki. I was able to just create a page and am not a contributor.

**Comment by BenMcH** [comment]
https://github.com/iambumblehead/form-urlencoded/wiki

**Comment by iambumblehead** [comment]
@BenMcH thank you I believe the wiki is disabled now

**Comment by iambumblehead** [comment]
@BenMcH please feel welcome to give any other recommendations you may have

**Comment by BenMcH** [comment]
Completely unrelated, but is there a changelog published anywhere?

**Comment by iambumblehead** [comment]
there is no changelog (there should be one, but there isn't)

**Comment by iambumblehead** [comment]
I'll add a changelog the next time there is an update @BenMcH
