### ISSUE TITLE
Using require default returns undefined in v4.5.0

### ISSUE THREAD

**Issue by TheTimeWalker** [iambumblehead/form-urlencoded#35]
With the newest release v4.5.0, the following line now returns an undefined:
`const formEncode = require('form-urlencoded').default`

Reverting to 4.4.2 works fine again. It seems like the changes for esm module support has broken it for CommonJS. Removing .default works fine actually: `const formEncode = require('form-urlencoded')` when on the latest version.

It now depends if this is a deliberate change. If yes, it would probably make more sense to bump it to v5 as it is a breaking change for any packages and projects that use `.default` import

**Comment by iambumblehead** [comment]
I apologize for the inconvenience I will try to resolve it by deprecating v4.5.0 and releasing v5.0.0

**Comment by iambumblehead** [comment]
@TheTimeWalker thank you. It should be resolved now and please feel free to re-open for any reason.
