### ISSUE TITLE
Brackets

### ISSUE THREAD

**Issue by christianswanepoel** [iambumblehead/form-urlencoded#40]
How do I output obj.prop2.prop3=elm as obj[prop2][prop3]=elm.

**Comment by iambumblehead** [comment]
@christianswanepoel this should do thee well
```javascript
console.log( formUrlencoded({
  obj: { prop2: { prop3: 'elm' } }
}).replace( /%5B/g, '[' ).replace( /%5D/g, ']' ) ) // "obj[prop2][prop3]=elm"
```

**Comment by christianswanepoel** [comment]
Thank you  @iambumblehead it works as advertised ;)
However does not work with a more complex sample :(

e.g
billing: {
    address: {
      line1: "10600 North Tantau Avenue",
      city: "Cupertino",
      postal_code: "95014",
      state: "CA",
      country: "US",
    },
  },

**Comment by iambumblehead** [comment]
```javascript
console.log( formUrlencoded({
  billing: {
    address: {
      line1: "10600 North Tantau Avenue",
      city: "Cupertino",
      postal_code: "95014",
      state: "CA",
      country: "US"
    }
  }
}).replace( /%5B/g, '[' ).replace( /%5D/g, ']' ) )
// billing[address][line1]=10600+North+Tantau+Avenue&billing[address][city]=
// Cupertino&billing[address][postal_code]=95014&billing[address][state]=CA&
// billing[address][country]=US
```
@christianswanepoel this looks correct to me. What am I missing? what other transformation do you want?

**Comment by iambumblehead** [comment]
@christianswanepoel feel free to re-open this issue for any reason
