### ISSUE TITLE
Bug: Issue with encoding spaces

### ISSUE THREAD

**Issue by KaydenMiller** [iambumblehead/form-urlencoded#43]
# Bug

## Repro Steps
Pass an object into the form-urlencoded function where at least one of the properties is a string and contains a space. That space will be replaced with a `+` when it should be `%20` as when you decode a `+` with url encoding it is still a `+`.

Example:
```js
const formurlencoded = require('form-urlencoded')

const str = formurlencoded({
  grant_type: 'grant_type:phone',
  phone_code: '585858',
  phone_number: '(318)  470-1137'
})

console.log(str)
// str will equal
// grant_type=urn%3Alyft%3Aoauth2%3Agrant_type%3Aphone&phone_code=718629&phone_number=%28318%29++470-1137
// and should be
// grant_type=urn%3Alyft%3Aoauth2%3Agrant_type%3Aphone&phone_code=718629&phone_number=%28318%29%20%20470-1137
```

**Comment by iambumblehead** [comment]
this is not a bug https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1
> Space characters are replaced by `+'

if you wish to use '%20' instead, call formurlencoded this way,
```
formurlencoded({
  grant_type: 'grant_type:phone',
  phone_code: '585858',
  phone_number: '(318)  470-1137'
}, {
  whitespace: '%20'
})
```
