### ISSUE TITLE
Option to ignore empty arrays

### ISSUE THREAD

**Issue by Sanva** [iambumblehead/form-urlencoded#47]
Hi!

I'm replacing some code using jQuery `ajax` method, and I find your package very useful for this endeavor — thanks a lot!

Would you consider adding an option to skip empty arrays? I can do it myself and make a PR if you want.

Best regards! :)

**Comment by iambumblehead** [comment]
Yes let's support skipping empty arrays. If you don't make a PR, I could make one tomorrow.

**Comment by iambumblehead** [comment]
ignoreEmptyArray is published to version 6.1.1 https://www.npmjs.com/package/form-urlencoded

thank you! :)

**Comment by iambumblehead** [comment]
ok thanks will publish it a fix as soon as possible

**Comment by Sanva** [comment]
Thanks! :)
