### ISSUE TITLE
Why Array data urlencoded need index number?

### ISSUE THREAD

**Issue by lidianhao123** [iambumblehead/form-urlencoded#8]
function arrnest(name, arr) {
        return arr.length ? filterjoin(arr.map(function (elem, index) {
            return nest(name + '[' + index + ']', elem);
        })) : encode(name + '[]');
    }
Data structure:
FCartId:[1,2,3,4,5,6]

After urlencoded:
FCartId[0]:1
FCartId[1]:2
FCartId[2]:3
FCartId[3]:4
FCartId[4]:5
FCartId[5]:6

I see jQuery serialize function return:
FCartId[]:1
FCartId[]:2
FCartId[]:3
FCartId[]:4
FCartId[]:5
FCartId[]:6

Looking for you reply!

**Comment by iambumblehead** [comment]
The index number is recently added by @jumper423 https://github.com/iambumblehead/form-urlencoded/pull/7

The Express web server software is able to parse strings which include the index number and so the pr was merged

**Comment by iambumblehead** [comment]
See the explanation from @jumper423 https://github.com/iambumblehead/form-urlencoded/pull/7#issuecomment-254368036

**Comment by lidianhao123** [comment]
Thinks. After check #7 I'm understand it.
